[colors.normal]
black = "#101111"
blue = "#2f80c5"
cyan = "#34d4ca"
green = "#26b92a"
magenta = "#b072c3"
red = "#e34545"
white = "#efefef"
yellow = "#f0c750"

[colors.primary]
background = "#252225"
foreground = "#cccfcc"

[cursor.style]
blinking = "On"
shape = "Beam"

[font]
size = 8

[font.normal]
family = "JetBrains Mono"

[window]
decorations = "none"
decorations_theme_variant = "Dark"
startup_mode = "Windowed"

[window.dimensions]
columns = 70
lines = 25

[scrolling]
history = 100000

[general]
import = [
  "~/.config/alacritty/custom-shell.toml"
]
